# Generated by Django 2.2.6 on 2019-10-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='pst_job',
            new_name='past_job',
        ),
    ]
